spring.application.name=EurekaClientDemo
#server.port=8080

# Each Eureka Server in the list must have different host name
eureka.client.serviceUrl.defaultZone=http://peer1:8761/eureka, http://peer2:8762/eureka, http://peer3:8763/eureka
#eureka.client.enabled=true