gateway.ip=127.0.0.1
login.url.path=/users/login
token.secret=NeSdAr2dNhNy3Edwl6XLe3sEYNRgWsm2ctw7XcQpLN4K1GbhB/6Z76zhVdiayYKaTgZT9KFcuFtgTwZi7Uj1dA==
token.expiration_time_millis=3600000
albums.url=http://ALBUMS-WS/users/%s/albums
